# Generated by Django 5.2.5 on 2025-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(related_name='exams', to='categories.category'),
        ),
    ]
