# Generated by Django 5.2.5 on 2025-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('quiz', '0002_exam_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exams', to='categories.category'),
        ),
    ]
