# Generated by Django 5.2.5 on 2025-08-27 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('manager', 'Project Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('tester', 'Tester')], default='developer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('avatar', models.URLField(blank=True, help_text='URL of profile picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
