# Generated by Django 5.2.5 on 2025-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_exam_categories'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='failed_questions',
            field=models.ManyToManyField(blank=True, to='quiz.question'),
        ),
    ]
